mmr: mmr.cpp config.h config.cpp Alignment.h Alignment.cpp GeneralData.h Utils.h Utils.cpp OnlineData.h OnlineData.cpp BatchData.h BatchData.cpp
	g++ -Wall -O9 -std=c++0x -pthread -o mmr mmr.cpp config.cpp Alignment.cpp Utils.cpp OnlineData.cpp BatchData.cpp
#	g++ -Wall -g -std=c++0x -pthread -o mmr mmr.cpp config.cpp Alignment.cpp Utils.cpp OnlineData.cpp BatchData.cpp
